### ISSUE TITLE
Hi. Very cool R blog but missing some links

### ISSUE THREAD

**Issue by juancsherrera** [anirudhjayaraman/anirudhjayaraman#1]
Dear Developer. I found your blog here: https://www.r-bloggers.com/endogenously-detecting-structural-breaks-in-a-time-series-implementation-in-r/ to be quite useful but I can't find the files. Would you mind pointing me in their direction?

**Comment by anirudhjayaraman** [comment]
Thanks. Here you go! https://github.com/anirudhjayaraman/strucchange_agri_productivity/blob/master/agricultural_productivity.xls

**Comment by juancsherrera** [comment]
Thank you so much. Very helpful
